name: Build & Sign Flutter APK

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.2"

      - name: Install dependencies
        run: flutter pub get

      - name: Decode keystore from base64
        run: |
          echo "${{ secrets.ANDROID_RELEASE_KEY }}" | base64 -d > android/app/my-release-key.jks

      - name: Create key.properties file
        run: |
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
          keyAlias=upload
          storeFile=my-release-key.jks
          EOF

      - name: Build Signed APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Rename APK for Release
        run: |
          mkdir -p build_output
          cp build/app/outputs/flutter-apk/app-release.apk build_output/app-release-${{ github.ref_name }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: build_output/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
