on:
  workflow_dispatch:
name: Build APK release
jobs:
  android-release-build:
    name: android-release-build
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:3.24.5
    steps:
      - uses: actions/checkout@v4
      - uses: NiklasLehnfeld/flutter-android-build-action@v2
        id: android-build
        with:
          release: true
          keystore: ${{ secrets.ANDROID_RELEASE_KEY }}
          keystore-pwd: "${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}"
          key-pwd: "${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}"
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ${{ steps.android-build.outputs.apk-path }}

  create-github-release:
    name: create-github-release
    runs-on: ubuntu-latest
    needs: [android-release-build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: release-apk
      - id: version
        uses: NiklasLehnfeld/flutter-version-number-action@v2
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.version.outputs.version-number }}
          title: ${{ steps.version.outputs.version-number }}
          files: |
            *.apk
